version: '3.8'

services:
  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/home/boo-foxy/Downloads/prometheus-2.52.0-rc.1.linux-amd64/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - nginx
  nginx:
    image: nginx:alpine
    volumes:
      - ./build:/usr/share/nginx/html
    ports:
      - "8000:80"
