name: Checkov Dockerfile Scan

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev



jobs:
  checkov-scan:
    runs-on: ubuntu-latest
    permissions:
      # required for all workflows
      security-events: write
      # only required for workflows in private repositories
      actions: read
      contents: read
      
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Checkov
      run: |
        python -m pip install --upgrade pip
        pip install checkov

    - name: Run Checkov scan
      run: |
        checkov -f ./Dockerfile -o sarif --output-file-path foo.sarif

    # - name: upload to Github artifacts
    #   uses: actions/upload-artifact@v3
    #   with:
    #     name: checkov-results
    #     path: checkov_results.json

    - name: Upload SARIF file
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: foo.sarif
