name: Checkov Dockerfile Scan

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  checkov-scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install Checkov
      run: |
        python -m pip install --upgrade pip
        pip install checkov

    - name: Run Checkov scan
      run: |
        checkov -f ./Dockerfile
